In [1]:
with open("task.txt","r") as f:
    data = f.read()

In [2]:
print(data)

GEORGE MCINTOSH
JOHN	ARCHER
MARKEETA	KLINEFELTER
JUDITH	BEAL
ROBERTO	REYES
JOANNE	KELDERMAN
FLEETA	ARTHUR
SHARON	JACOBS
LELA	FARMER
CATHERINE	EVANS
COURTNEY	CAIN
MARCIA	SEIFRIG
SARAH	MORRIS
MARY	AMOS
JERRY	COURTS
REVEL	MASSIE
GLORIA	WISEMAN
EDNA	MCFALL
DOREEN	HARMON
JAMES	HOWARD
DAVID	BOOE
SUSAN	PROUGH
STEVE	MILLER
VICTORIANO	RAMIREZ
ANDREW	COSENTINO
BRENDA	SALLEE
SYLVIA	SCROGGINS
JO	DOYLE
VICKY	MATTHIAS
CRAIG	SAPONKA
ROBERT	JERINA
MELISSA	STUTSMAN
STEVEN	KROUSE
MIKE	FRAZEE
JULIAN	CHASTAIN
MARVIN	VAN
VICKI	BELL
JANE	LENTINE
APRIL	SCHWARTZ
CHERYL	WASHINGTON
JOHNNIE	STANSON
LINDA	DONNELLY
CLARA	HOLMES
CAROLYN	KETCHEM
POLLY	SHULL
THERESA	HANDSHOE
CONSTANCE	KRESS
NORA	CASSIDY
ANN	HARGETT
WILLIAM	THOMASON
LORI	HELTON
ALBERTA	BEAVER
K	ROGERS
DELORES	RAGENS
JEANETTE	KACZMAREK
BARBARA	NAVE
JON	CROWE
DAPHNE	ROSS
LYNN	HAYES
CATHY	ALLEN
ED	NEWTON
KIM	CASE
PATRICIA	BUNNER
CHRISTIE	MCCLENDON
JESSE	ALEXANDER
DANIEL	SEXTON
DOROTHY	BLACKWELL
WILLIE	BATTEN
SONNA	BALL
RENOVA	SCOTT
ROSETTA	KENAR
TERESA	READY
BONNIE	GREEN
CHARLES	WILSON
BETTY	NELSON
WANDA	WILLIAMS
RICHARD	PLOUGH
JOSEPH	CLOWER
STELLA	CAGLE
SANDRA	HOFFMAN
MARTHA	PREBLE
DENNIS	PAPENLEUR
N	THOMPSON
MICHAEL	KUHN
JANNIE	BARNES
GREGORY	CRONKHITE
DIANE	HARRIS
KATHY	SMITH
PAUL	CANTWELL
LARRY	HUFF
THOMAS	RAGOZZINO
MARLENE	ANTHONY
LUANNE	MADISON
CURTIS	DURANCZYK
DEANNA	LEGLER
DONNA	BOYD
KENNETH	FEHR
ROGER	PERKINS
HENRY	KOSMOSKI

In [3]:
listt = data.split()

In [4]:
print(listt)

['GEORGE', 'MCINTOSH', 'JOHN', 'ARCHER', 'MARKEETA', 'KLINEFELTER', 'JUDITH', 'BEAL', 'ROBERTO', 'REYES', 'JOANNE', 'KELDERMAN', 'FLEETA', 'ARTHUR', 'SHARON', 'JACOBS', 'LELA', 'FARMER', 'CATHERINE', 'EVANS', 'COURTNEY', 'CAIN', 'MARCIA', 'SEIFRIG', 'SARAH', 'MORRIS', 'MARY', 'AMOS', 'JERRY', 'COURTS', 'REVEL', 'MASSIE', 'GLORIA', 'WISEMAN', 'EDNA', 'MCFALL', 'DOREEN', 'HARMON', 'JAMES', 'HOWARD', 'DAVID', 'BOOE', 'SUSAN', 'PROUGH', 'STEVE', 'MILLER', 'VICTORIANO', 'RAMIREZ', 'ANDREW', 'COSENTINO', 'BRENDA', 'SALLEE', 'SYLVIA', 'SCROGGINS', 'JO', 'DOYLE', 'VICKY', 'MATTHIAS', 'CRAIG', 'SAPONKA', 'ROBERT', 'JERINA', 'MELISSA', 'STUTSMAN', 'STEVEN', 'KROUSE', 'MIKE', 'FRAZEE', 'JULIAN', 'CHASTAIN', 'MARVIN', 'VAN', 'VICKI', 'BELL', 'JANE', 'LENTINE', 'APRIL', 'SCHWARTZ', 'CHERYL', 'WASHINGTON', 'JOHNNIE', 'STANSON', 'LINDA', 'DONNELLY', 'CLARA', 'HOLMES', 'CAROLYN', 'KETCHEM', 'POLLY', 'SHULL', 'THERESA', 'HANDSHOE', 'CONSTANCE', 'KRESS', 'NORA', 'CASSIDY', 'ANN', 'HARGETT', 'WILLIAM', 'THOMASON', 'LORI', 'HELTON', 'ALBERTA', 'BEAVER', 'K', 'ROGERS', 'DELORES', 'RAGENS', 'JEANETTE', 'KACZMAREK', 'BARBARA', 'NAVE', 'JON', 'CROWE', 'DAPHNE', 'ROSS', 'LYNN', 'HAYES', 'CATHY', 'ALLEN', 'ED', 'NEWTON', 'KIM', 'CASE', 'PATRICIA', 'BUNNER', 'CHRISTIE', 'MCCLENDON', 'JESSE', 'ALEXANDER', 'DANIEL', 'SEXTON', 'DOROTHY', 'BLACKWELL', 'WILLIE', 'BATTEN', 'SONNA', 'BALL', 'RENOVA', 'SCOTT', 'ROSETTA', 'KENAR', 'TERESA', 'READY', 'BONNIE', 'GREEN', 'CHARLES', 'WILSON', 'BETTY', 'NELSON', 'WANDA', 'WILLIAMS', 'RICHARD', 'PLOUGH', 'JOSEPH', 'CLOWER', 'STELLA', 'CAGLE', 'SANDRA', 'HOFFMAN', 'MARTHA', 'PREBLE', 'DENNIS', 'PAPENLEUR', 'N', 'THOMPSON', 'MICHAEL', 'KUHN', 'JANNIE', 'BARNES', 'GREGORY', 'CRONKHITE', 'DIANE', 'HARRIS', 'KATHY', 'SMITH', 'PAUL', 'CANTWELL', 'LARRY', 'HUFF', 'THOMAS', 'RAGOZZINO', 'MARLENE', 'ANTHONY', 'LUANNE', 'MADISON', 'CURTIS', 'DURANCZYK', 'DEANNA', 'LEGLER', 'DONNA', 'BOYD', 'KENNETH', 'FEHR', 'ROGER', 'PERKINS', 'HENRY', 'KOSMOSKI']

In [5]:
for count,i in enumerate(listt):
    print(count)
    print(i)

0
GEORGE
1
MCINTOSH
2
JOHN
3
ARCHER
4
MARKEETA
5
KLINEFELTER
6
JUDITH
7
BEAL
8
ROBERTO
9
REYES
10
JOANNE
11
KELDERMAN
12
FLEETA
13
ARTHUR
14
SHARON
15
JACOBS
16
LELA
17
FARMER
18
CATHERINE
19
EVANS
20
COURTNEY
21
CAIN
22
MARCIA
23
SEIFRIG
24
SARAH
25
MORRIS
26
MARY
27
AMOS
28
JERRY
29
COURTS
30
REVEL
31
MASSIE
32
GLORIA
33
WISEMAN
34
EDNA
35
MCFALL
36
DOREEN
37
HARMON
38
JAMES
39
HOWARD
40
DAVID
41
BOOE
42
SUSAN
43
PROUGH
44
STEVE
45
MILLER
46
VICTORIANO
47
RAMIREZ
48
ANDREW
49
COSENTINO
50
BRENDA
51
SALLEE
52
SYLVIA
53
SCROGGINS
54
JO
55
DOYLE
56
VICKY
57
MATTHIAS
58
CRAIG
59
SAPONKA
60
ROBERT
61
JERINA
62
MELISSA
63
STUTSMAN
64
STEVEN
65
KROUSE
66
MIKE
67
FRAZEE
68
JULIAN
69
CHASTAIN
70
MARVIN
71
VAN
72
VICKI
73
BELL
74
JANE
75
LENTINE
76
APRIL
77
SCHWARTZ
78
CHERYL
79
WASHINGTON
80
JOHNNIE
81
STANSON
82
LINDA
83
DONNELLY
84
CLARA
85
HOLMES
86
CAROLYN
87
KETCHEM
88
POLLY
89
SHULL
90
THERESA
91
HANDSHOE
92
CONSTANCE
93
KRESS
94
NORA
95
CASSIDY
96
ANN
97
HARGETT
98
WILLIAM
99
THOMASON
100
LORI
101
HELTON
102
ALBERTA
103
BEAVER
104
K
105
ROGERS
106
DELORES
107
RAGENS
108
JEANETTE
109
KACZMAREK
110
BARBARA
111
NAVE
112
JON
113
CROWE
114
DAPHNE
115
ROSS
116
LYNN
117
HAYES
118
CATHY
119
ALLEN
120
ED
121
NEWTON
122
KIM
123
CASE
124
PATRICIA
125
BUNNER
126
CHRISTIE
127
MCCLENDON
128
JESSE
129
ALEXANDER
130
DANIEL
131
SEXTON
132
DOROTHY
133
BLACKWELL
134
WILLIE
135
BATTEN
136
SONNA
137
BALL
138
RENOVA
139
SCOTT
140
ROSETTA
141
KENAR
142
TERESA
143
READY
144
BONNIE
145
GREEN
146
CHARLES
147
WILSON
148
BETTY
149
NELSON
150
WANDA
151
WILLIAMS
152
RICHARD
153
PLOUGH
154
JOSEPH
155
CLOWER
156
STELLA
157
CAGLE
158
SANDRA
159
HOFFMAN
160
MARTHA
161
PREBLE
162
DENNIS
163
PAPENLEUR
164
N
165
THOMPSON
166
MICHAEL
167
KUHN
168
JANNIE
169
BARNES
170
GREGORY
171
CRONKHITE
172
DIANE
173
HARRIS
174
KATHY
175
SMITH
176
PAUL
177
CANTWELL
178
LARRY
179
HUFF
180
THOMAS
181
RAGOZZINO
182
MARLENE
183
ANTHONY
184
LUANNE
185
MADISON
186
CURTIS
187
DURANCZYK
188
DEANNA
189
LEGLER
190
DONNA
191
BOYD
192
KENNETH
193
FEHR
194
ROGER
195
PERKINS
196
HENRY
197
KOSMOSKI

In [76]:
first_names = []

In [81]:
for j in range(0,197,2):
    print(listt[j])
    first_names.append(listt[j])

GEORGE
JOHN
MARKEETA
JUDITH
ROBERTO
JOANNE
FLEETA
SHARON
LELA
CATHERINE
COURTNEY
MARCIA
SARAH
MARY
JERRY
REVEL
GLORIA
EDNA
DOREEN
JAMES
DAVID
SUSAN
STEVE
VICTORIANO
ANDREW
BRENDA
SYLVIA
JO
VICKY
CRAIG
ROBERT
MELISSA
STEVEN
MIKE
JULIAN
MARVIN
VICKI
JANE
APRIL
CHERYL
JOHNNIE
LINDA
CLARA
CAROLYN
POLLY
THERESA
CONSTANCE
NORA
ANN
WILLIAM
LORI
ALBERTA
K
DELORES
JEANETTE
BARBARA
JON
DAPHNE
LYNN
CATHY
ED
KIM
PATRICIA
CHRISTIE
JESSE
DANIEL
DOROTHY
WILLIE
SONNA
RENOVA
ROSETTA
TERESA
BONNIE
CHARLES
BETTY
WANDA
RICHARD
JOSEPH
STELLA
SANDRA
MARTHA
DENNIS
N
MICHAEL
JANNIE
GREGORY
DIANE
KATHY
PAUL
LARRY
THOMAS
MARLENE
LUANNE
CURTIS
DEANNA
DONNA
KENNETH
ROGER
HENRY

In [78]:
last_names = []

In [83]:
for i in range(1,197,2):
    print(listt[i])
    last_names.append(listt[i])

MCINTOSH
ARCHER
KLINEFELTER
BEAL
REYES
KELDERMAN
ARTHUR
JACOBS
FARMER
EVANS
CAIN
SEIFRIG
MORRIS
AMOS
COURTS
MASSIE
WISEMAN
MCFALL
HARMON
HOWARD
BOOE
PROUGH
MILLER
RAMIREZ
COSENTINO
SALLEE
SCROGGINS
DOYLE
MATTHIAS
SAPONKA
JERINA
STUTSMAN
KROUSE
FRAZEE
CHASTAIN
VAN
BELL
LENTINE
SCHWARTZ
WASHINGTON
STANSON
DONNELLY
HOLMES
KETCHEM
SHULL
HANDSHOE
KRESS
CASSIDY
HARGETT
THOMASON
HELTON
BEAVER
ROGERS
RAGENS
KACZMAREK
NAVE
CROWE
ROSS
HAYES
ALLEN
NEWTON
CASE
BUNNER
MCCLENDON
ALEXANDER
SEXTON
BLACKWELL
BATTEN
BALL
SCOTT
KENAR
READY
GREEN
WILSON
NELSON
WILLIAMS
PLOUGH
CLOWER
CAGLE
HOFFMAN
PREBLE
PAPENLEUR
THOMPSON
KUHN
BARNES
CRONKHITE
HARRIS
SMITH
CANTWELL
HUFF
RAGOZZINO
ANTHONY
MADISON
DURANCZYK
LEGLER
BOYD
FEHR
PERKINS

In [82]:
first_names

['GEORGE',
 'JOHN',
 'MARKEETA',
 'JUDITH',
 'ROBERTO',
 'JOANNE',
 'FLEETA',
 'SHARON',
 'LELA',
 'CATHERINE',
 'COURTNEY',
 'MARCIA',
 'SARAH',
 'MARY',
 'JERRY',
 'REVEL',
 'GLORIA',
 'EDNA',
 'DOREEN',
 'JAMES',
 'DAVID',
 'SUSAN',
 'STEVE',
 'VICTORIANO',
 'ANDREW',
 'BRENDA',
 'SYLVIA',
 'JO',
 'VICKY',
 'CRAIG',
 'ROBERT',
 'MELISSA',
 'STEVEN',
 'MIKE',
 'JULIAN',
 'MARVIN',
 'VICKI',
 'JANE',
 'APRIL',
 'CHERYL',
 'JOHNNIE',
 'LINDA',
 'CLARA',
 'CAROLYN',
 'POLLY',
 'THERESA',
 'CONSTANCE',
 'NORA',
 'ANN',
 'WILLIAM',
 'LORI',
 'ALBERTA',
 'K',
 'DELORES',
 'JEANETTE',
 'BARBARA',
 'JON',
 'DAPHNE',
 'LYNN',
 'CATHY',
 'ED',
 'KIM',
 'PATRICIA',
 'CHRISTIE',
 'JESSE',
 'DANIEL',
 'DOROTHY',
 'WILLIE',
 'SONNA',
 'RENOVA',
 'ROSETTA',
 'TERESA',
 'BONNIE',
 'CHARLES',
 'BETTY',
 'WANDA',
 'RICHARD',
 'JOSEPH',
 'STELLA',
 'SANDRA',
 'MARTHA',
 'DENNIS',
 'N',
 'MICHAEL',
 'JANNIE',
 'GREGORY',
 'DIANE',
 'KATHY',
 'PAUL',
 'LARRY',
 'THOMAS',
 'MARLENE',
 'LUANNE',
 'CURTIS',
 'DEANNA',
 'DONNA',
 'KENNETH',
 'ROGER',
 'HENRY']

In [84]:
last_names

['MCINTOSH',
 'ARCHER',
 'KLINEFELTER',
 'BEAL',
 'REYES',
 'KELDERMAN',
 'ARTHUR',
 'JACOBS',
 'FARMER',
 'EVANS',
 'CAIN',
 'SEIFRIG',
 'MORRIS',
 'AMOS',
 'COURTS',
 'MASSIE',
 'WISEMAN',
 'MCFALL',
 'HARMON',
 'HOWARD',
 'BOOE',
 'PROUGH',
 'MILLER',
 'RAMIREZ',
 'COSENTINO',
 'SALLEE',
 'SCROGGINS',
 'DOYLE',
 'MATTHIAS',
 'SAPONKA',
 'JERINA',
 'STUTSMAN',
 'KROUSE',
 'FRAZEE',
 'CHASTAIN',
 'VAN',
 'BELL',
 'LENTINE',
 'SCHWARTZ',
 'WASHINGTON',
 'STANSON',
 'DONNELLY',
 'HOLMES',
 'KETCHEM',
 'SHULL',
 'HANDSHOE',
 'KRESS',
 'CASSIDY',
 'HARGETT',
 'THOMASON',
 'HELTON',
 'BEAVER',
 'ROGERS',
 'RAGENS',
 'KACZMAREK',
 'NAVE',
 'CROWE',
 'ROSS',
 'HAYES',
 'ALLEN',
 'NEWTON',
 'CASE',
 'BUNNER',
 'MCCLENDON',
 'ALEXANDER',
 'SEXTON',
 'BLACKWELL',
 'BATTEN',
 'BALL',
 'SCOTT',
 'KENAR',
 'READY',
 'GREEN',
 'WILSON',
 'NELSON',
 'WILLIAMS',
 'PLOUGH',
 'CLOWER',
 'CAGLE',
 'HOFFMAN',
 'PREBLE',
 'PAPENLEUR',
 'THOMPSON',
 'KUHN',
 'BARNES',
 'CRONKHITE',
 'HARRIS',
 'SMITH',
 'CANTWELL',
 'HUFF',
 'RAGOZZINO',
 'ANTHONY',
 'MADISON',
 'DURANCZYK',
 'LEGLER',
 'BOYD',
 'FEHR',
 'PERKINS']

In [88]:
for i in first_names:
    for j in last_names:
        res = i + " " + j
        with open("all_names.txt", "a") as f:
            f.write("\n" + res)